services:  
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin
      DOCKER_INFLUXDB_INIT_ORG: p3-org
      DOCKER_INFLUXDB_INIT_BUCKET: energy-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: super-secret-token
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana

  sensor-simulator:
    container_name: sensor-simulator
    build:
      context: .
      dockerfile: sensor-simulator/SensorSimulator/Dockerfile
    environment:
      Dataset__FilePath: /data/household_power_consumption_sample.txt
      Dataset__MaxReadings: 50
      Dataset__DelayMs: 2000
      EdgeX__BaseUrl: http://edgex-device-rest:59986/api/v3/resource
      EdgeX__DeviceName: smart-meter-1
    volumes:
      - ./dataset:/data:ro
    networks:
      - edgex-network

  visualization-service:
    container_name: visualization-service
    build:
      context: .
      dockerfile: visualization-service/VisualizationService/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mqtt__Host: edgex-mqtt-broker
      Mqtt__Port: 1883
      Mqtt__Topic: edgex/events/#
      InfluxDb__Url: http://influxdb:8086
      InfluxDb__Token: super-secret-token
      InfluxDb__Org: p3-org
      InfluxDb__Bucket: energy-bucket
    depends_on:
      - influxdb
    networks:
      - default
      - edgex-network
  
  monitoring-service:
    container_name: monitoring-service
    build:
      context: .
      dockerfile: monitoring-service/MonitoringService/Dockerfile
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mqtt__Host: edgex-mqtt-broker
      Mqtt__Port: 1883
      Mqtt__Topic: edgex/events/#
    networks:
      - edgex-network

networks:
  edgex-network:
    external: true
    name: edgex_edgex-network